---

# Which user get which ssh key:
users:
  l3d:
   - l3d@backup.l3d.yt
   - l3d@derpy.l3d.yt
   - l3d@mobile.l3d.yt
   - l3d@pinkie.l3d.yt
   - l3d@business.wingcon.com


# admins on local device:
admins:
  - l3d

# users createt on this host
accounts:
  - l3d

ssh_public_key_store: 'admin_ssh_keys'
home_sweet_home: false

