---

- name: secure access to toolbox gateway
  hosts: motion
  tags:
  - access
  - ssh
  - auth
  - newuser
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'ansible'

- name: install some fancy packages
  hosts: motion
  tags:
  - setup
  - base
  roles:
   - base-packages

- name: create a fancy feature complete home
  hosts: motion
  tags:
  - setup
  - base
  - home
  - newuser
  roles:
   - dotfiles
   - install-bat

- name: Install motion on cluster
  hosts: 
    - cluster.tbbs.me
    - webcam2.tbbs.me
  become: true
  tags:
  - video
  - motion
  - cctv
  roles:
   - motion

