---

- name: secure access to toolbox gateway
  hosts: motion
  tags:
  - access
  - ssh
  - auth
  - newuser
  roles:
   - ssh-auth
   - sshd
  vars:
    - ansible_ssh_user: 'ansible'

- name: install some fancy packages
  hosts: motion
  tags:
  - setup
  - base
  roles:
   - base-packages

- name: create a fancy feature complete home
  hosts: motion
  tags:
  - setup
  - base
  - home
  - newuser
  roles:
   - dotfiles


- name: create a fancy feature complete home
  hosts: 
    - cluster.tbbs.me
  tags:
  - bat
  roles:
   - install-bat

- name: Prepare motion on pi
  hosts: 
    - webcam2.tbbs.me
    - webcam3.tbbs.me
  become: true
  tags:
  - tmpfs
  roles:
   - tmpfs

- name: Install motion on cluster.tbbs.me
  hosts: 
    - cluster.tbbs.me
  become: true
  tags:
  - video
  - motion
  - cctv
  roles:
   - motion

# you still have to deploy motion from sources, because rasbian binary is tooo old (again)
# todo: von alex ein motion.deb packet für den pi bauen lassen, dann geht die motion rolle auch wieder!


