---
# default users for SSH access
sshd_default_allowed_users:
  - "root"
  - "ansible"
  - "alex"
  - "cam"

# don't forget to add the ssh_access group!
sshd_default_allowed_groups:
  - "root"
  - "admins"
  - "alex"
  - "cam"
